"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, CalendarDays, Check, Clock3, Download, Eye, FileText, History, Link2, Paperclip, Pencil, Plus, Send, Trash2, UserRound } from "lucide-react";
import { Button, Card, ConfirmDialog, FormField, Modal, priorityTones, Progress, projectStatusTones, StatusBadge, Tabs } from "@/components";
import { assignedProjects, projectDetailsMock } from "@/mock-data";
import type { IdeaPriority, ProjectStatus, StatusTone } from "@/types";

const tabs = ["نظرة عامة", "المتطلبات", "الجدول الزمني", "التحديثات", "المرفقات", "سجل النشاط"];
const statusTones = projectStatusTones;
const requirementTones: Record<string, StatusTone> = { "مفتوح": "neutral", "قيد التنفيذ": "info", "مكتمل": "success", "متعثر": "danger" };
const milestoneTones: Record<string, StatusTone> = { "لم يبدأ": "neutral", "قيد التنفيذ": "info", "مكتمل": "success", "متأخر": "danger" };
const inputClass = "min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm text-slate-800";
const textareaClass = `${inputClass} min-h-28 py-3 leading-6`;

type Requirement = { id: number; title: string; description: string; priority: string; status: string; dueDate: string; assignee: string };
type Milestone = { id: number; title: string; date: string; status: string };
type Update = { id: number; date: string; author: string; text: string; attachment: string | null };
type Attachment = { id: number; name: string; type: string; size: string; uploadedBy: string; date: string };
type Activity = { id: number; title: string; detail: string; actor: string; date: string };

function SectionTitle({ title, description, action }: { title: string; description?: string; action?: React.ReactNode }) {
  return <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-bold text-slate-900">{title}</h2>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{action}</div>;
}

function Detail({ label, children }: { label: string; children: React.ReactNode }) {
  return <div><p className="text-xs font-semibold text-slate-500">{label}</p><div className="mt-2 text-sm leading-7 text-slate-800">{children}</div></div>;
}

export function ProjectDetailsClient({ id }: { id: string }) {
  const listProject = assignedProjects.find(project => project.id === id) ?? assignedProjects[0];
  const [activeTab, setActiveTab] = useState(tabs[0]);
  const [projectStatus, setProjectStatus] = useState<ProjectStatus>(listProject.status);
  const [requirements, setRequirements] = useState<Requirement[]>(projectDetailsMock.requirements.map(item => ({ ...item })));
  const [milestones, setMilestones] = useState<Milestone[]>(projectDetailsMock.milestones.map(item => ({ ...item })));
  const [updates, setUpdates] = useState<Update[]>(projectDetailsMock.updates.map(item => ({ ...item })));
  const [attachments, setAttachments] = useState<Attachment[]>(projectDetailsMock.attachments.map(item => ({ ...item })));
  const [activity, setActivity] = useState<Activity[]>(projectDetailsMock.activity.map(item => ({ ...item })));
  const [stakeholders, setStakeholders] = useState<string[]>([...projectDetailsMock.stakeholders]);
  const [stakeholderDraft, setStakeholderDraft] = useState("");
  const [requirementModal, setRequirementModal] = useState(false);
  const [editingRequirement, setEditingRequirement] = useState<number | null>(null);
  const [requirementForm, setRequirementForm] = useState({ title: "", description: "", priority: "متوسطة", status: "مفتوح", dueDate: "", assignee: "" });
  const [updateModal, setUpdateModal] = useState(false);
  const [updateForm, setUpdateForm] = useState({ text: "", attachment: "" });
  const [success, setSuccess] = useState("");
  const [pendingAttachmentDelete, setPendingAttachmentDelete] = useState<number | null>(null);

  const notify = (message: string) => { setSuccess(message); window.setTimeout(() => setSuccess(""), 3500); };
  const addActivity = (title: string, detail: string) => setActivity(current => [{ id: Date.now(), title, detail, actor: "سارة الأحمد", date: "6 أغسطس 2026، الآن" }, ...current]);
  const openNewRequirement = () => { setEditingRequirement(null); setRequirementForm({ title: "", description: "", priority: "متوسطة", status: "مفتوح", dueDate: "", assignee: "" }); setRequirementModal(true); };
  const editRequirement = (item: Requirement) => { setEditingRequirement(item.id); setRequirementForm({ title: item.title, description: item.description, priority: item.priority, status: item.status, dueDate: item.dueDate, assignee: item.assignee }); setRequirementModal(true); };
  const saveRequirement = () => { if (editingRequirement) setRequirements(current => current.map(item => item.id === editingRequirement ? { ...item, ...requirementForm } : item)); else setRequirements(current => [{ id: Date.now(), ...requirementForm }, ...current]); addActivity(editingRequirement ? "تم تعديل متطلب" : "تمت إضافة متطلب", requirementForm.title); setRequirementModal(false); notify(editingRequirement ? "تم تحديث المتطلب محليًا." : "تمت إضافة المتطلب محليًا."); };
  const changeRequirementStatus = (item: Requirement, status: string) => { setRequirements(current => current.map(row => row.id === item.id ? { ...row, status } : row)); addActivity("تم تحديث حالة متطلب", `${item.title} — ${status}`); notify("تم تحديث حالة المتطلب."); };
  const changeMilestone = (item: Milestone, status: string) => { setMilestones(current => current.map(row => row.id === item.id ? { ...row, status } : row)); addActivity("تم تعديل الجدول الزمني", `${item.title} — ${status}`); notify("تم تحديث المرحلة الزمنية."); };
  const addUpdate = () => { setUpdates(current => [{ id: Date.now(), date: "6 أغسطس 2026، الآن", author: "سارة الأحمد", text: updateForm.text, attachment: updateForm.attachment || null }, ...current]); addActivity("تمت إضافة تحديث للمشروع", updateForm.text.slice(0, 60)); setUpdateForm({ text: "", attachment: "" }); setUpdateModal(false); notify("تمت إضافة تحديث المشروع."); };
  const uploadAttachments = (files: FileList | null) => { if (!files) return; const added = Array.from(files).map((file, index) => ({ id: Date.now() + index, name: file.name, type: file.name.split(".").pop()?.toUpperCase() ?? "FILE", size: `${Math.max(1, Math.round(file.size / 1024))} KB`, uploadedBy: "سارة الأحمد", date: "6 أغسطس 2026" })); setAttachments(current => [...added, ...current]); added.forEach(file => addActivity("تم رفع مرفق", file.name)); notify("تم رفع المرفقات محليًا."); };
  const deleteAttachment = (item: Attachment) => setPendingAttachmentDelete(item.id);
  const confirmAttachmentDelete = () => { const item=attachments.find(file=>file.id===pendingAttachmentDelete); if(!item)return; setAttachments(current=>current.filter(file=>file.id!==item.id)); addActivity("تم حذف مرفق",item.name); notify("تم حذف المرفق محليًا."); };

  return <div className="mx-auto max-w-[1500px]">
    {success && <div role="status" className="fixed left-5 top-20 z-50 flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800 shadow-card"><Check className="h-4 w-4"/>{success}</div>}
    <Link href="/innovation-specialist/projects" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-brand-700"><ArrowRight className="h-4 w-4"/>العودة إلى المشاريع</Link>

    <div className="mb-6 flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold text-brand-700">{id}</span><StatusBadge tone={statusTones[projectStatus]}>{projectStatus}</StatusBadge><StatusBadge tone={priorityTones[listProject.priority]}>{listProject.priority}</StatusBadge></div><h1 className="mt-3 text-2xl font-bold leading-9 text-slate-900">{listProject.name}</h1><div className="mt-3 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-500"><span className="inline-flex items-center gap-2"><Link2 className="h-4 w-4"/>الفكرة: <Link href={`/innovation-specialist/ideas/${listProject.ideaId}`} className="font-semibold text-brand-700">{listProject.ideaTitle}</Link></span><span className="inline-flex items-center gap-2"><UserRound className="h-4 w-4"/>{listProject.manager}</span><span className="inline-flex items-center gap-2"><Clock3 className="h-4 w-4"/>آخر تحديث: {listProject.lastUpdate}</span></div><div className="mt-4 max-w-md"><Progress value={listProject.completion}/></div></div><div className="flex flex-wrap items-center gap-2"><select aria-label="تحديث حالة المشروع" value={projectStatus} onChange={event => { const next = event.target.value as ProjectStatus; setProjectStatus(next); addActivity("تم تغيير حالة المشروع", `إلى ${next}`); notify("تم تحديث حالة المشروع محليًا."); }} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option>قيد التخطيط</option><option>قيد التنفيذ</option><option>متعثر</option><option>معلق</option><option>مكتمل</option></select><Button onClick={()=>setUpdateModal(true)}><Plus className="h-4 w-4"/>إضافة تحديث</Button><Button variant="secondary" onClick={()=>setActiveTab("الجدول الزمني")}>تحديث الجدول الزمني</Button><Button variant="secondary" onClick={()=>setActiveTab("المتطلبات")}>إدارة المتطلبات</Button></div></div>

    <Card className="p-0"><Tabs tabs={tabs} active={activeTab} onChange={setActiveTab}/></Card>

    {activeTab === "نظرة عامة" && <div className="mt-6 grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-6"><Card><SectionTitle title="ملخص المشروع"/><p className="text-sm leading-7 text-slate-700">{projectDetailsMock.summary}</p><div className="mt-6 grid gap-6 md:grid-cols-2"><Detail label="الهدف التشغيلي">{projectDetailsMock.businessObjective}</Detail><Detail label="الهدف الاستراتيجي">{projectDetailsMock.strategicObjective}</Detail><Detail label="الفكرة المرتبطة"><Link href={`/innovation-specialist/ideas/${listProject.ideaId}`} className="font-semibold text-brand-700">{listProject.ideaTitle}</Link></Detail><Detail label="مالك المشروع">{projectDetailsMock.owner}</Detail><Detail label="المرحلة الحالية">{listProject.phase}</Detail><Detail label="الميزانية التقديرية">{projectDetailsMock.budget}</Detail><Detail label="تاريخ البدء">{projectDetailsMock.startDate}</Detail><Detail label="الإنجاز المتوقع">{projectDetailsMock.expectedCompletion}</Detail></div></Card><Card><SectionTitle title="النتائج المتوقعة"/><div className="grid gap-3 sm:grid-cols-2">{projectDetailsMock.expectedOutcomes.map(item=><div key={item} className="flex items-start gap-2 rounded-lg border border-slate-200 p-3 text-sm"><Check className="mt-0.5 h-4 w-4 shrink-0 text-brand-700"/>{item}</div>)}</div></Card></div><Card><SectionTitle title="أصحاب المصلحة" description="يمكنك اقتراح أصحاب مصلحة للمشروع."/><div className="space-y-2">{stakeholders.map(item=><div key={item} className="flex items-center gap-2 rounded-lg bg-slate-50 p-3 text-sm"><UserRound className="h-4 w-4 text-brand-700"/>{item}</div>)}</div><div className="mt-4 flex gap-2"><input value={stakeholderDraft} onChange={event=>setStakeholderDraft(event.target.value)} placeholder="اسم الإدارة أو الجهة" className={inputClass}/><Button className="shrink-0" onClick={()=>{if(!stakeholderDraft.trim())return;setStakeholders(current=>[...current,stakeholderDraft]);addActivity("تم اقتراح صاحب مصلحة",stakeholderDraft);setStakeholderDraft("");notify("تمت إضافة المقترح محليًا.");}}>اقتراح</Button></div></Card></div>}

    {activeTab === "المتطلبات" && <div className="mt-6"><SectionTitle title="متطلبات المشروع" description="إدارة المتطلبات التشغيلية ومتابعة المسؤوليات ومواعيد الاستحقاق." action={<Button onClick={openNewRequirement}><Plus className="h-4 w-4"/>إضافة متطلب</Button>}/><div className="grid gap-4 lg:grid-cols-2">{requirements.map(item=><Card key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-slate-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p></div><StatusBadge tone={priorityTones[item.priority as IdeaPriority]}>{item.priority}</StatusBadge></div><div className="mt-5 grid grid-cols-2 gap-4 border-t border-slate-100 pt-4 text-sm"><Detail label="تاريخ الاستحقاق">{item.dueDate}</Detail><Detail label="المسؤول">{item.assignee}</Detail></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><select aria-label={`حالة ${item.title}`} value={item.status} onChange={event=>changeRequirementStatus(item,event.target.value)} className="h-9 rounded-lg border border-slate-300 bg-white px-3 text-xs"><option>مفتوح</option><option>قيد التنفيذ</option><option>مكتمل</option><option>متعثر</option></select><div className="flex items-center gap-2"><StatusBadge tone={requirementTones[item.status]}>{item.status}</StatusBadge><Button variant="ghost" className="min-h-9 px-3" onClick={()=>editRequirement(item)}><Pencil className="h-4 w-4"/>تعديل</Button></div></div></Card>)}</div></div>}

    {activeTab === "الجدول الزمني" && <div className="mt-6"><SectionTitle title="الجدول الزمني للتنفيذ" description="حدّث حالة كل مرحلة وفق تقدم المشروع الفعلي."/><Card><div className="grid gap-0 lg:grid-cols-6">{milestones.map((item,index)=><div key={item.id} className="relative pb-8 pr-8 last:pb-0 lg:pb-0 lg:pr-0 lg:pt-10"><span className={`absolute right-0 top-1 z-10 grid h-6 w-6 place-items-center rounded-full ring-4 lg:right-1/2 lg:top-0 lg:translate-x-1/2 ${item.status==="مكتمل"?"bg-brand-700 text-white ring-brand-50":item.status==="قيد التنفيذ"?"bg-amber-500 text-white ring-amber-50":"bg-slate-200 text-slate-500 ring-slate-50"}`}>{item.status==="مكتمل"&&<Check className="h-3.5 w-3.5"/>}</span>{index<milestones.length-1&&<span className="absolute right-[11px] top-7 h-full w-0.5 bg-slate-200 lg:right-1/2 lg:top-3 lg:h-0.5 lg:w-full"/>}<div className="lg:px-3 lg:text-center"><h3 className="text-sm font-bold">{item.title}</h3><p className="mt-1 text-xs text-slate-500">{item.date}</p><StatusBadge tone={milestoneTones[item.status]}>{item.status}</StatusBadge><select aria-label={`تحديث ${item.title}`} value={item.status} onChange={event=>changeMilestone(item,event.target.value)} className="mt-3 h-9 w-full rounded-lg border border-slate-300 bg-white px-2 text-xs"><option>لم يبدأ</option><option>قيد التنفيذ</option><option>مكتمل</option><option>متأخر</option></select></div></div>)}</div></Card></div>}

    {activeTab === "التحديثات" && <div className="mt-6"><SectionTitle title="تحديثات المشروع" description="آخر المستجدات مرتبة من الأحدث إلى الأقدم." action={<Button onClick={()=>setUpdateModal(true)}><Plus className="h-4 w-4"/>إضافة تحديث</Button>}/><div className="space-y-4">{updates.map(item=><Card key={item.id}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-brand-50 text-brand-700"><UserRound className="h-5 w-5"/></span><div><p className="text-sm font-bold">{item.author}</p><p className="text-xs text-slate-500">{item.date}</p></div></div></div><p className="mt-4 text-sm leading-7 text-slate-700">{item.text}</p>{item.attachment&&<button className="mt-4 inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-brand-700"><Paperclip className="h-4 w-4"/>{item.attachment}</button>}</Card>)}</div></div>}

    {activeTab === "المرفقات" && <div className="mt-6"><SectionTitle title="مرفقات المشروع" description="الوثائق والملفات الداعمة المرتبطة بالتنفيذ." action={<label className="inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-lg bg-brand-700 px-4 text-sm font-semibold text-white hover:bg-brand-800"><Plus className="h-4 w-4"/>رفع مرفق<input type="file" multiple className="sr-only" onChange={event=>uploadAttachments(event.target.files)}/></label>}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{attachments.map(item=><Card key={item.id}><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-brand-50 text-brand-700"><FileText className="h-5 w-5"/></span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold">{item.name}</h3><p className="mt-1 text-xs text-slate-500">{item.type} • {item.size}</p></div></div><div className="mt-4 border-t border-slate-100 pt-3 text-xs text-slate-500"><p>رفع بواسطة {item.uploadedBy}</p><p className="mt-1">{item.date}</p></div><div className="mt-4 flex gap-2"><Button variant="secondary" className="min-h-9 flex-1 px-3 text-xs" onClick={()=>notify(`معاينة ${item.name}`)}><Eye className="h-4 w-4"/>معاينة</Button><Button variant="ghost" className="min-h-9 px-3 text-red-600" onClick={()=>deleteAttachment(item)}><Trash2 className="h-4 w-4"/>حذف</Button></div></Card>)}</div></div>}

    {activeTab === "سجل النشاط" && <div className="mt-6"><SectionTitle title="سجل نشاط المشروع" description="جميع التغييرات والإجراءات مرتبة من الأحدث إلى الأقدم."/><Card><div>{activity.map((item,index)=><div key={item.id} className="relative flex gap-4 pb-7 last:pb-0"><span className="relative z-10 mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-full bg-brand-50 text-brand-700 ring-4 ring-white"><History className="h-4 w-4"/></span>{index<activity.length-1&&<span className="absolute right-[15px] top-9 h-full w-px bg-slate-200"/>}<div><p className="text-sm font-bold">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.detail}</p><p className="mt-1.5 text-xs text-slate-400">{item.actor} • {item.date}</p></div></div>)}</div></Card></div>}

    <Modal open={requirementModal} title={editingRequirement ? "تعديل المتطلب" : "إضافة متطلب"} onClose={()=>setRequirementModal(false)}><div className="space-y-4"><FormField label="عنوان المتطلب"><input className={inputClass} value={requirementForm.title} onChange={event=>setRequirementForm(current=>({...current,title:event.target.value}))}/></FormField><FormField label="الوصف"><textarea className={textareaClass} value={requirementForm.description} onChange={event=>setRequirementForm(current=>({...current,description:event.target.value}))}/></FormField><div className="grid gap-4 sm:grid-cols-2"><FormField label="الأولوية"><select className={inputClass} value={requirementForm.priority} onChange={event=>setRequirementForm(current=>({...current,priority:event.target.value}))}><option>عاجلة</option><option>عالية</option><option>متوسطة</option><option>منخفضة</option></select></FormField><FormField label="الحالة"><select className={inputClass} value={requirementForm.status} onChange={event=>setRequirementForm(current=>({...current,status:event.target.value}))}><option>مفتوح</option><option>قيد التنفيذ</option><option>مكتمل</option><option>متعثر</option></select></FormField><FormField label="تاريخ الاستحقاق"><input type="date" className={inputClass} value={requirementForm.dueDate} onChange={event=>setRequirementForm(current=>({...current,dueDate:event.target.value}))}/></FormField><FormField label="المسؤول"><input className={inputClass} value={requirementForm.assignee} onChange={event=>setRequirementForm(current=>({...current,assignee:event.target.value}))}/></FormField></div><div className="flex justify-end gap-2 pt-3"><Button variant="secondary" onClick={()=>setRequirementModal(false)}>إلغاء</Button><Button onClick={saveRequirement}>حفظ المتطلب</Button></div></div></Modal>

    <Modal open={updateModal} title="إضافة تحديث للمشروع" onClose={()=>setUpdateModal(false)}><div className="space-y-4"><FormField label="نص التحديث"><textarea className={textareaClass} value={updateForm.text} onChange={event=>setUpdateForm(current=>({...current,text:event.target.value}))} placeholder="اكتب آخر مستجدات المشروع..."/></FormField><FormField label="مرفق اختياري"><input className={inputClass} value={updateForm.attachment} onChange={event=>setUpdateForm(current=>({...current,attachment:event.target.value}))} placeholder="اسم الملف الداعم"/></FormField><div className="flex justify-end gap-2 pt-3"><Button variant="secondary" onClick={()=>setUpdateModal(false)}>إلغاء</Button><Button onClick={addUpdate}><Send className="h-4 w-4"/>إضافة التحديث</Button></div></div></Modal>
    <ConfirmDialog open={pendingAttachmentDelete!==null} title="حذف المرفق" description="سيُحذف هذا المرفق من قائمة المشروع المحلية. هل تريد المتابعة؟" confirmLabel="حذف" danger onClose={()=>setPendingAttachmentDelete(null)} onConfirm={confirmAttachmentDelete}/>
  </div>;
}

