"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect } from "react";
import { Bell,ChartNoAxesCombined,FolderKanban,House,Lightbulb,LogOut,UserRound,X } from "lucide-react";
import { specialistProfile } from "@/mock-data";
import type { NavigationItem } from "@/types";
const nav:NavigationItem[]=[{label:"الرئيسية",href:"/innovation-specialist/dashboard",icon:House},{label:"الأفكار",href:"/innovation-specialist/ideas",icon:Lightbulb},{label:"المشاريع",href:"/innovation-specialist/projects",icon:FolderKanban},{label:"التقارير",href:"/innovation-specialist/reports",icon:ChartNoAxesCombined},{label:"الإشعارات",href:"/innovation-specialist/notifications",icon:Bell},{label:"الملف الشخصي",href:"/innovation-specialist/profile",icon:UserRound}];
export function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){const path=usePathname();useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[onClose,open]);return <><button aria-label="إغلاق القائمة" onClick={onClose} className={`fixed inset-0 z-30 bg-slate-950/30 lg:hidden ${open?"block":"hidden"}`}/><aside aria-label="التنقل الرئيسي" className={`fixed inset-y-0 right-0 z-40 flex w-72 flex-col border-l border-slate-200 bg-white transition-transform lg:translate-x-0 ${open?"translate-x-0":"translate-x-full"}`}><div className="flex h-20 items-center justify-between border-b px-6"><div><p className="text-xl font-black text-brand-800">مـنـارة</p><p className="text-xs text-slate-500">إدارة الابتكار</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100 lg:hidden" aria-label="إغلاق"><X className="h-5 w-5"/></button></div><nav aria-label="صفحات مسؤول الابتكار" className="flex-1 space-y-1 overflow-y-auto p-4">{nav.map(i=>{const active=path===i.href||(i.href!==nav[0].href&&path.startsWith(i.href+"/"));const Icon=i.icon;return <Link aria-current={active?"page":undefined} onClick={onClose} key={i.href} href={i.href} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold ${active?"bg-brand-50 text-brand-800":"text-slate-600 hover:bg-slate-50"}`}><Icon className="h-5 w-5"/>{i.label}</Link>})}</nav><div className="border-t p-4"><Link aria-current={path==="/innovation-specialist/profile"?"page":undefined} href="/innovation-specialist/profile" className={`flex items-center gap-3 rounded-lg p-3 ${path==="/innovation-specialist/profile"?"bg-brand-50":"hover:bg-slate-50"}`}><span className="grid h-10 w-10 place-items-center rounded-full bg-brand-100 text-sm font-bold text-brand-800">{specialistProfile.initials}</span><span><span className="block text-sm font-semibold">{specialistProfile.name}</span><span className="block text-xs text-slate-500">{specialistProfile.role}</span></span></Link><Link href="/" className="mt-2 flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50"><LogOut className="h-5 w-5"/>تسجيل الخروج</Link></div></aside></>}
