"use client";
import { Search, X } from "lucide-react";
import Link from "next/link";
import { useEffect, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode } from "react";
import type { StatusTone } from "@/types";
const cx=(...c:Array<string|false|null|undefined>)=>c.filter(Boolean).join(" ");
export function Card({children,className=""}:{children:ReactNode;className?:string}){return <section className={cx("rounded-xl border border-slate-200 bg-white p-5 shadow-card",className)}>{children}</section>}
export function KpiCard({label,value,icon,context,href}:{label:string;value:string|number;icon?:ReactNode;context?:string;href?:string}){const content=<Card className="h-full transition-colors hover:border-brand-100 hover:bg-brand-50/30"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value}</p></div>{icon}</div>{context&&<p className="mt-4 text-xs leading-5 text-slate-500">{context}</p>}</Card>;return href?<Link href={href} className="block h-full rounded-xl focus-visible:outline-none">{content}</Link>:content}
export function Button({children,variant="primary",className="",type="button",...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"}){const v={primary:"bg-brand-700 text-white hover:bg-brand-800",secondary:"border border-slate-300 bg-white text-slate-700 hover:bg-slate-50",ghost:"text-slate-600 hover:bg-slate-100"};return <button type={type} className={cx("inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-4 text-sm font-semibold transition-colors disabled:cursor-not-allowed disabled:opacity-50",v[variant],className)} {...props}>{children}</button>}
export function StatusBadge({children,tone="neutral"}:{children:ReactNode;tone?:StatusTone}){const t={neutral:"bg-slate-100 text-slate-700",success:"bg-emerald-50 text-emerald-700",warning:"bg-amber-50 text-amber-700",danger:"bg-red-50 text-red-700",info:"bg-sky-50 text-sky-700"};return <span className={cx("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold",t[tone])}>{children}</span>}
export function Progress({value,label=true}:{value:number;label?:boolean}){const safe=Math.max(0,Math.min(100,value));return <div className="flex min-w-28 items-center gap-2" role="progressbar" aria-label="نسبة الاكتمال" aria-valuemin={0} aria-valuemax={100} aria-valuenow={safe}><span className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><span className="block h-full rounded-full bg-brand-600" style={{width:`${safe}%`}}/></span>{label&&<span className="w-9 text-left text-xs font-semibold text-slate-600">{safe}%</span>}</div>}
export function SearchInput(props:InputHTMLAttributes<HTMLInputElement>){return <label className="relative block"><span className="sr-only">بحث</span><Search className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className="h-10 w-full rounded-lg border border-slate-300 bg-white pr-10 pl-3 text-sm" placeholder="بحث..." {...props}/></label>}
export function Filters({children}:{children:ReactNode}){return <div className="flex flex-wrap items-center gap-2">{children}</div>}
export function Tabs({tabs,active,onChange}:{tabs:string[];active:string;onChange?:(tab:string)=>void}){return <div className="flex gap-1 overflow-x-auto border-b border-slate-200" role="tablist">{tabs.map(t=><button type="button" role="tab" aria-selected={t===active} onClick={()=>onChange?.(t)} key={t} className={cx("whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium",t===active?"border-brand-700 text-brand-700":"border-transparent text-slate-500 hover:text-slate-700")}>{t}</button>)}</div>}
export function FormField({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-2 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label>}
export function EmptyState({title,description,icon,actions}:{title:string;description:string;icon?:ReactNode;actions?:ReactNode}){return <div className="flex min-h-64 flex-col items-center justify-center rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center">{icon}<h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 max-w-md text-sm text-slate-500">{description}</p>{actions&&<div className="mt-5">{actions}</div>}</div>}
export function DataTable({headers,children}:{headers:string[];children?:ReactNode}){return <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white" tabIndex={0} aria-label="جدول بيانات قابل للتمرير أفقيًا"><table className="min-w-full text-right text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{headers.map(h=><th scope="col" key={h} className="whitespace-nowrap px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
export function Modal({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}){useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};document.addEventListener("keydown",close);const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=previous}},[onClose,open]);if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/40 p-4" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><Card className="my-auto w-full max-w-lg"><div className="mb-5 flex items-center justify-between gap-4"><h2 id="modal-title" className="text-lg font-bold">{title}</h2><button type="button" onClick={onClose} aria-label="إغلاق" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X className="h-5 w-5"/></button></div>{children}</Card></div>}
export function ConfirmDialog({open,title,description,confirmLabel="تأكيد",cancelLabel="إلغاء",danger=false,onConfirm,onClose}:{open:boolean;title:string;description:string;confirmLabel?:string;cancelLabel?:string;danger?:boolean;onConfirm:()=>void;onClose:()=>void}){return <Modal open={open} title={title} onClose={onClose}><p className="text-sm leading-6 text-slate-600">{description}</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>{cancelLabel}</Button><Button className={danger?"bg-red-600 hover:bg-red-700":""} onClick={()=>{onConfirm();onClose()}}>{confirmLabel}</Button></div></Modal>}
